/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FilesRouteImport } from './routes/files'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as PodcastCountryRouteImport } from './routes/podcast/$country'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as PodcastCountryIdRouteImport } from './routes/podcast/$country/$id'
import { Route as FilesFolderFolderIdRouteImport } from './routes/files/folder/$folderId'
import { Route as PodcastCountryIdIndexRouteImport } from './routes/podcast/$country/$id/index'
import { Route as PodcastCountryIdEpisodesRouteImport } from './routes/podcast/$country/$id/episodes'
import { Route as PodcastCountryIdEpisodeKeyRouteImport } from './routes/podcast/$country/$id/$episodeKey'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilesRoute,
} as any)
const PodcastCountryRoute = PodcastCountryRouteImport.update({
  id: '/podcast/$country',
  path: '/podcast/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const PodcastCountryIdRoute = PodcastCountryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PodcastCountryRoute,
} as any)
const FilesFolderFolderIdRoute = FilesFolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => FilesRoute,
} as any)
const PodcastCountryIdIndexRoute = PodcastCountryIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PodcastCountryIdRoute,
} as any)
const PodcastCountryIdEpisodesRoute =
  PodcastCountryIdEpisodesRouteImport.update({
    id: '/episodes',
    path: '/episodes',
    getParentRoute: () => PodcastCountryIdRoute,
  } as any)
const PodcastCountryIdEpisodeKeyRoute =
  PodcastCountryIdEpisodeKeyRouteImport.update({
    id: '/$episodeKey',
    path: '/$episodeKey',
    getParentRoute: () => PodcastCountryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/files': typeof FilesRouteWithChildren
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRouteWithChildren
  '/ops': typeof OpsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/podcast/$country': typeof PodcastCountryRouteWithChildren
  '/files/': typeof FilesIndexRoute
  '/files/folder/$folderId': typeof FilesFolderFolderIdRoute
  '/podcast/$country/$id': typeof PodcastCountryIdRouteWithChildren
  '/podcast/$country/$id/$episodeKey': typeof PodcastCountryIdEpisodeKeyRoute
  '/podcast/$country/$id/episodes': typeof PodcastCountryIdEpisodesRoute
  '/podcast/$country/$id/': typeof PodcastCountryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRouteWithChildren
  '/ops': typeof OpsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/podcast/$country': typeof PodcastCountryRouteWithChildren
  '/files': typeof FilesIndexRoute
  '/files/folder/$folderId': typeof FilesFolderFolderIdRoute
  '/podcast/$country/$id/$episodeKey': typeof PodcastCountryIdEpisodeKeyRoute
  '/podcast/$country/$id/episodes': typeof PodcastCountryIdEpisodesRoute
  '/podcast/$country/$id': typeof PodcastCountryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/files': typeof FilesRouteWithChildren
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRouteWithChildren
  '/ops': typeof OpsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/podcast/$country': typeof PodcastCountryRouteWithChildren
  '/files/': typeof FilesIndexRoute
  '/files/folder/$folderId': typeof FilesFolderFolderIdRoute
  '/podcast/$country/$id': typeof PodcastCountryIdRouteWithChildren
  '/podcast/$country/$id/$episodeKey': typeof PodcastCountryIdEpisodeKeyRoute
  '/podcast/$country/$id/episodes': typeof PodcastCountryIdEpisodesRoute
  '/podcast/$country/$id/': typeof PodcastCountryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/explore'
    | '/favorites'
    | '/files'
    | '/history'
    | '/legal'
    | '/ops'
    | '/search'
    | '/settings'
    | '/subscriptions'
    | '/legal/privacy'
    | '/legal/terms'
    | '/podcast/$country'
    | '/files/'
    | '/files/folder/$folderId'
    | '/podcast/$country/$id'
    | '/podcast/$country/$id/$episodeKey'
    | '/podcast/$country/$id/episodes'
    | '/podcast/$country/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/explore'
    | '/favorites'
    | '/history'
    | '/legal'
    | '/ops'
    | '/search'
    | '/settings'
    | '/subscriptions'
    | '/legal/privacy'
    | '/legal/terms'
    | '/podcast/$country'
    | '/files'
    | '/files/folder/$folderId'
    | '/podcast/$country/$id/$episodeKey'
    | '/podcast/$country/$id/episodes'
    | '/podcast/$country/$id'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/explore'
    | '/favorites'
    | '/files'
    | '/history'
    | '/legal'
    | '/ops'
    | '/search'
    | '/settings'
    | '/subscriptions'
    | '/legal/privacy'
    | '/legal/terms'
    | '/podcast/$country'
    | '/files/'
    | '/files/folder/$folderId'
    | '/podcast/$country/$id'
    | '/podcast/$country/$id/$episodeKey'
    | '/podcast/$country/$id/episodes'
    | '/podcast/$country/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  FilesRoute: typeof FilesRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  LegalRoute: typeof LegalRouteWithChildren
  OpsRoute: typeof OpsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  PodcastCountryRoute: typeof PodcastCountryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof FilesRoute
    }
    '/podcast/$country': {
      id: '/podcast/$country'
      path: '/podcast/$country'
      fullPath: '/podcast/$country'
      preLoaderRoute: typeof PodcastCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/podcast/$country/$id': {
      id: '/podcast/$country/$id'
      path: '/$id'
      fullPath: '/podcast/$country/$id'
      preLoaderRoute: typeof PodcastCountryIdRouteImport
      parentRoute: typeof PodcastCountryRoute
    }
    '/files/folder/$folderId': {
      id: '/files/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/files/folder/$folderId'
      preLoaderRoute: typeof FilesFolderFolderIdRouteImport
      parentRoute: typeof FilesRoute
    }
    '/podcast/$country/$id/': {
      id: '/podcast/$country/$id/'
      path: '/'
      fullPath: '/podcast/$country/$id/'
      preLoaderRoute: typeof PodcastCountryIdIndexRouteImport
      parentRoute: typeof PodcastCountryIdRoute
    }
    '/podcast/$country/$id/episodes': {
      id: '/podcast/$country/$id/episodes'
      path: '/episodes'
      fullPath: '/podcast/$country/$id/episodes'
      preLoaderRoute: typeof PodcastCountryIdEpisodesRouteImport
      parentRoute: typeof PodcastCountryIdRoute
    }
    '/podcast/$country/$id/$episodeKey': {
      id: '/podcast/$country/$id/$episodeKey'
      path: '/$episodeKey'
      fullPath: '/podcast/$country/$id/$episodeKey'
      preLoaderRoute: typeof PodcastCountryIdEpisodeKeyRouteImport
      parentRoute: typeof PodcastCountryIdRoute
    }
  }
}

interface FilesRouteChildren {
  FilesIndexRoute: typeof FilesIndexRoute
  FilesFolderFolderIdRoute: typeof FilesFolderFolderIdRoute
}

const FilesRouteChildren: FilesRouteChildren = {
  FilesIndexRoute: FilesIndexRoute,
  FilesFolderFolderIdRoute: FilesFolderFolderIdRoute,
}

const FilesRouteWithChildren = FilesRoute._addFileChildren(FilesRouteChildren)

interface LegalRouteChildren {
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface PodcastCountryIdRouteChildren {
  PodcastCountryIdEpisodeKeyRoute: typeof PodcastCountryIdEpisodeKeyRoute
  PodcastCountryIdEpisodesRoute: typeof PodcastCountryIdEpisodesRoute
  PodcastCountryIdIndexRoute: typeof PodcastCountryIdIndexRoute
}

const PodcastCountryIdRouteChildren: PodcastCountryIdRouteChildren = {
  PodcastCountryIdEpisodeKeyRoute: PodcastCountryIdEpisodeKeyRoute,
  PodcastCountryIdEpisodesRoute: PodcastCountryIdEpisodesRoute,
  PodcastCountryIdIndexRoute: PodcastCountryIdIndexRoute,
}

const PodcastCountryIdRouteWithChildren =
  PodcastCountryIdRoute._addFileChildren(PodcastCountryIdRouteChildren)

interface PodcastCountryRouteChildren {
  PodcastCountryIdRoute: typeof PodcastCountryIdRouteWithChildren
}

const PodcastCountryRouteChildren: PodcastCountryRouteChildren = {
  PodcastCountryIdRoute: PodcastCountryIdRouteWithChildren,
}

const PodcastCountryRouteWithChildren = PodcastCountryRoute._addFileChildren(
  PodcastCountryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  FilesRoute: FilesRouteWithChildren,
  HistoryRoute: HistoryRoute,
  LegalRoute: LegalRouteWithChildren,
  OpsRoute: OpsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  PodcastCountryRoute: PodcastCountryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
