/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FilesRouteImport } from './routes/files'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as CountryRouteImport } from './routes/$country'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as FilesFolderFolderIdRouteImport } from './routes/files/folder/$folderId'
import { Route as CountryPodcastIdRouteImport } from './routes/$country/podcast/$id'
import { Route as CountryPodcastIdIndexRouteImport } from './routes/$country/podcast/$id/index'
import { Route as CountryPodcastIdEpisodesRouteImport } from './routes/$country/podcast/$id/episodes'
import { Route as CountryPodcastIdEpisodeEpisodeIdRouteImport } from './routes/$country/podcast/$id/episode/$episodeId'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryRoute = CountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilesRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const FilesFolderFolderIdRoute = FilesFolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => FilesRoute,
} as any)
const CountryPodcastIdRoute = CountryPodcastIdRouteImport.update({
  id: '/podcast/$id',
  path: '/podcast/$id',
  getParentRoute: () => CountryRoute,
} as any)
const CountryPodcastIdIndexRoute = CountryPodcastIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryPodcastIdRoute,
} as any)
const CountryPodcastIdEpisodesRoute =
  CountryPodcastIdEpisodesRouteImport.update({
    id: '/episodes',
    path: '/episodes',
    getParentRoute: () => CountryPodcastIdRoute,
  } as any)
const CountryPodcastIdEpisodeEpisodeIdRoute =
  CountryPodcastIdEpisodeEpisodeIdRouteImport.update({
    id: '/episode/$episodeId',
    path: '/episode/$episodeId',
    getParentRoute: () => CountryPodcastIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$country': typeof CountryRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/files': typeof FilesRouteWithChildren
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRouteWithChildren
  '/ops': typeof OpsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/files/': typeof FilesIndexRoute
  '/$country/podcast/$id': typeof CountryPodcastIdRouteWithChildren
  '/files/folder/$folderId': typeof FilesFolderFolderIdRoute
  '/$country/podcast/$id/episodes': typeof CountryPodcastIdEpisodesRoute
  '/$country/podcast/$id/': typeof CountryPodcastIdIndexRoute
  '/$country/podcast/$id/episode/$episodeId': typeof CountryPodcastIdEpisodeEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$country': typeof CountryRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRouteWithChildren
  '/ops': typeof OpsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/files': typeof FilesIndexRoute
  '/files/folder/$folderId': typeof FilesFolderFolderIdRoute
  '/$country/podcast/$id/episodes': typeof CountryPodcastIdEpisodesRoute
  '/$country/podcast/$id': typeof CountryPodcastIdIndexRoute
  '/$country/podcast/$id/episode/$episodeId': typeof CountryPodcastIdEpisodeEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$country': typeof CountryRouteWithChildren
  '/downloads': typeof DownloadsRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/files': typeof FilesRouteWithChildren
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRouteWithChildren
  '/ops': typeof OpsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/files/': typeof FilesIndexRoute
  '/$country/podcast/$id': typeof CountryPodcastIdRouteWithChildren
  '/files/folder/$folderId': typeof FilesFolderFolderIdRoute
  '/$country/podcast/$id/episodes': typeof CountryPodcastIdEpisodesRoute
  '/$country/podcast/$id/': typeof CountryPodcastIdIndexRoute
  '/$country/podcast/$id/episode/$episodeId': typeof CountryPodcastIdEpisodeEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$country'
    | '/downloads'
    | '/explore'
    | '/favorites'
    | '/files'
    | '/history'
    | '/legal'
    | '/ops'
    | '/search'
    | '/settings'
    | '/subscriptions'
    | '/legal/privacy'
    | '/legal/terms'
    | '/files/'
    | '/$country/podcast/$id'
    | '/files/folder/$folderId'
    | '/$country/podcast/$id/episodes'
    | '/$country/podcast/$id/'
    | '/$country/podcast/$id/episode/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$country'
    | '/downloads'
    | '/explore'
    | '/favorites'
    | '/history'
    | '/legal'
    | '/ops'
    | '/search'
    | '/settings'
    | '/subscriptions'
    | '/legal/privacy'
    | '/legal/terms'
    | '/files'
    | '/files/folder/$folderId'
    | '/$country/podcast/$id/episodes'
    | '/$country/podcast/$id'
    | '/$country/podcast/$id/episode/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/$country'
    | '/downloads'
    | '/explore'
    | '/favorites'
    | '/files'
    | '/history'
    | '/legal'
    | '/ops'
    | '/search'
    | '/settings'
    | '/subscriptions'
    | '/legal/privacy'
    | '/legal/terms'
    | '/files/'
    | '/$country/podcast/$id'
    | '/files/folder/$folderId'
    | '/$country/podcast/$id/episodes'
    | '/$country/podcast/$id/'
    | '/$country/podcast/$id/episode/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryRoute: typeof CountryRouteWithChildren
  DownloadsRoute: typeof DownloadsRoute
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  FilesRoute: typeof FilesRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  LegalRoute: typeof LegalRouteWithChildren
  OpsRoute: typeof OpsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country': {
      id: '/$country'
      path: '/$country'
      fullPath: '/$country'
      preLoaderRoute: typeof CountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof FilesRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/files/folder/$folderId': {
      id: '/files/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/files/folder/$folderId'
      preLoaderRoute: typeof FilesFolderFolderIdRouteImport
      parentRoute: typeof FilesRoute
    }
    '/$country/podcast/$id': {
      id: '/$country/podcast/$id'
      path: '/podcast/$id'
      fullPath: '/$country/podcast/$id'
      preLoaderRoute: typeof CountryPodcastIdRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/podcast/$id/': {
      id: '/$country/podcast/$id/'
      path: '/'
      fullPath: '/$country/podcast/$id/'
      preLoaderRoute: typeof CountryPodcastIdIndexRouteImport
      parentRoute: typeof CountryPodcastIdRoute
    }
    '/$country/podcast/$id/episodes': {
      id: '/$country/podcast/$id/episodes'
      path: '/episodes'
      fullPath: '/$country/podcast/$id/episodes'
      preLoaderRoute: typeof CountryPodcastIdEpisodesRouteImport
      parentRoute: typeof CountryPodcastIdRoute
    }
    '/$country/podcast/$id/episode/$episodeId': {
      id: '/$country/podcast/$id/episode/$episodeId'
      path: '/episode/$episodeId'
      fullPath: '/$country/podcast/$id/episode/$episodeId'
      preLoaderRoute: typeof CountryPodcastIdEpisodeEpisodeIdRouteImport
      parentRoute: typeof CountryPodcastIdRoute
    }
  }
}

interface CountryPodcastIdRouteChildren {
  CountryPodcastIdEpisodesRoute: typeof CountryPodcastIdEpisodesRoute
  CountryPodcastIdIndexRoute: typeof CountryPodcastIdIndexRoute
  CountryPodcastIdEpisodeEpisodeIdRoute: typeof CountryPodcastIdEpisodeEpisodeIdRoute
}

const CountryPodcastIdRouteChildren: CountryPodcastIdRouteChildren = {
  CountryPodcastIdEpisodesRoute: CountryPodcastIdEpisodesRoute,
  CountryPodcastIdIndexRoute: CountryPodcastIdIndexRoute,
  CountryPodcastIdEpisodeEpisodeIdRoute: CountryPodcastIdEpisodeEpisodeIdRoute,
}

const CountryPodcastIdRouteWithChildren =
  CountryPodcastIdRoute._addFileChildren(CountryPodcastIdRouteChildren)

interface CountryRouteChildren {
  CountryPodcastIdRoute: typeof CountryPodcastIdRouteWithChildren
}

const CountryRouteChildren: CountryRouteChildren = {
  CountryPodcastIdRoute: CountryPodcastIdRouteWithChildren,
}

const CountryRouteWithChildren =
  CountryRoute._addFileChildren(CountryRouteChildren)

interface FilesRouteChildren {
  FilesIndexRoute: typeof FilesIndexRoute
  FilesFolderFolderIdRoute: typeof FilesFolderFolderIdRoute
}

const FilesRouteChildren: FilesRouteChildren = {
  FilesIndexRoute: FilesIndexRoute,
  FilesFolderFolderIdRoute: FilesFolderFolderIdRoute,
}

const FilesRouteWithChildren = FilesRoute._addFileChildren(FilesRouteChildren)

interface LegalRouteChildren {
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryRoute: CountryRouteWithChildren,
  DownloadsRoute: DownloadsRoute,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  FilesRoute: FilesRouteWithChildren,
  HistoryRoute: HistoryRoute,
  LegalRoute: LegalRouteWithChildren,
  OpsRoute: OpsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
