packages:
  - 'apps/*'
overrides:
  basic-ftp: ^5.2.0
  next@>=16.1.0-canary.0 <16.1.5: ^16.1.5
  '@isaacs/brace-expansion': ^5.0.1
  minimatch@<3.1.4: ^3.1.4
  minimatch@>=5.0.0 <5.1.8: ^5.1.8
  minimatch@>=9.0.0 <9.0.7: ^9.0.7
  minimatch@>=10.0.0 <10.2.3: ^10.2.3
  rollup@<2.80.0: ^2.80.0
  rollup@>=4.0.0 <4.59.0: ^4.59.0
  serialize-javascript: ^7.0.3
  music-metadata: ^11.12.3
allowBuilds:
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
