// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type PodcastCacheState struct {
	PodcastItunesID           string
	IsTruncated               int64
	LastSuccessfulFetchAtUnix int64
	LastAttemptedFetchAtUnix  int64
	RefreshNotBeforeUnix      int64
	FetchFailCount            int64
	LastErrorClass            sql.NullString
	ApproxBytes               int64
	Priority                  int64
	LastAccessedAtUnix        int64
}

type PodcastEpisode struct {
	PodcastItunesID string
	EpisodeGuid     string
	Title           string
	Description     string
	EnclosureUrl    string
	PublishedAtUnix int64
	DurationSeconds int64
	Image           sql.NullString
	EpisodeNumber   sql.NullInt64
	SeasonNumber    sql.NullInt64
	EpisodeType     sql.NullString
	Explicit        sql.NullInt64
	Link            sql.NullString
	EnclosureLength sql.NullInt64
	TranscriptUrl   sql.NullString
	CreatedAtUnix   int64
	UpdatedAtUnix   int64
}

type PodcastEpisodesFt struct {
	PodcastItunesID string
	EpisodeGuid     string
	Title           string
	Description     string
	PodcastTitle    string
	PodcastAuthor   string
}

type PodcastEpisodesFtsIndex struct {
	ID              int64
	PodcastItunesID string
	EpisodeGuid     string
}

type PodcastShow struct {
	PodcastItunesID        string
	Title                  string
	Description            string
	Author                 sql.NullString
	Image                  sql.NullString
	FeedUrl                sql.NullString
	Language               sql.NullString
	CategoriesJson         sql.NullString
	EpisodeCountHint       sql.NullInt64
	FeedLastUpdateTimeUnix int64
	CreatedAtUnix          int64
	UpdatedAtUnix          int64
}

type PodcastShowsFt struct {
	PodcastItunesID string
	Title           string
	Author          string
	Description     string
	Categories      string
}

type PodcastShowsFtsIndex struct {
	ID              int64
	PodcastItunesID string
}
