// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pi_episode_cache.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deletePIEpisodesForPodcast = `-- name: DeletePIEpisodesForPodcast :exec
DELETE FROM podcast_episodes WHERE podcast_itunes_id = ?1
`

func (q *Queries) DeletePIEpisodesForPodcast(ctx context.Context, podcastItunesID string) error {
	_, err := q.db.ExecContext(ctx, deletePIEpisodesForPodcast, podcastItunesID)
	return err
}

const deletePIPodcastShow = `-- name: DeletePIPodcastShow :exec
DELETE FROM podcast_shows WHERE podcast_itunes_id = ?1
`

func (q *Queries) DeletePIPodcastShow(ctx context.Context, podcastItunesID string) error {
	_, err := q.db.ExecContext(ctx, deletePIPodcastShow, podcastItunesID)
	return err
}

const getPIEpisodeByGuid = `-- name: GetPIEpisodeByGuid :one
SELECT
  podcast_itunes_id,
  episode_guid,
  title,
  description,
  enclosure_url,
  published_at_unix,
  duration_seconds,
  image,
  episode_number,
  season_number,
  episode_type,
  explicit,
  link,
  enclosure_length,
  transcript_url,
  created_at_unix,
  updated_at_unix
FROM podcast_episodes
WHERE podcast_itunes_id = ?1 AND episode_guid = ?2
`

type GetPIEpisodeByGuidParams struct {
	PodcastItunesID string
	EpisodeGuid     string
}

func (q *Queries) GetPIEpisodeByGuid(ctx context.Context, arg GetPIEpisodeByGuidParams) (PodcastEpisode, error) {
	row := q.db.QueryRowContext(ctx, getPIEpisodeByGuid, arg.PodcastItunesID, arg.EpisodeGuid)
	var i PodcastEpisode
	err := row.Scan(
		&i.PodcastItunesID,
		&i.EpisodeGuid,
		&i.Title,
		&i.Description,
		&i.EnclosureUrl,
		&i.PublishedAtUnix,
		&i.DurationSeconds,
		&i.Image,
		&i.EpisodeNumber,
		&i.SeasonNumber,
		&i.EpisodeType,
		&i.Explicit,
		&i.Link,
		&i.EnclosureLength,
		&i.TranscriptUrl,
		&i.CreatedAtUnix,
		&i.UpdatedAtUnix,
	)
	return i, err
}

const getPIEpisodePageMetadata = `-- name: GetPIEpisodePageMetadata :one
SELECT
  (SELECT COUNT(*) FROM podcast_episodes episodes WHERE episodes.podcast_itunes_id = ?1) AS total_count,
  state.is_truncated,
  state.last_successful_fetch_at_unix,
  state.refresh_not_before_unix
FROM podcast_cache_state state
WHERE state.podcast_itunes_id = ?1
`

type GetPIEpisodePageMetadataRow struct {
	TotalCount                int64
	IsTruncated               int64
	LastSuccessfulFetchAtUnix int64
	RefreshNotBeforeUnix      int64
}

func (q *Queries) GetPIEpisodePageMetadata(ctx context.Context, podcastItunesID string) (GetPIEpisodePageMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getPIEpisodePageMetadata, podcastItunesID)
	var i GetPIEpisodePageMetadataRow
	err := row.Scan(
		&i.TotalCount,
		&i.IsTruncated,
		&i.LastSuccessfulFetchAtUnix,
		&i.RefreshNotBeforeUnix,
	)
	return i, err
}

const getPINewestEpisodePublishedAtUnix = `-- name: GetPINewestEpisodePublishedAtUnix :one
SELECT published_at_unix
FROM podcast_episodes
WHERE podcast_itunes_id = ?1
ORDER BY published_at_unix DESC
LIMIT 1
`

func (q *Queries) GetPINewestEpisodePublishedAtUnix(ctx context.Context, podcastItunesID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPINewestEpisodePublishedAtUnix, podcastItunesID)
	var published_at_unix int64
	err := row.Scan(&published_at_unix)
	return published_at_unix, err
}

const getPIPodcastMetadata = `-- name: GetPIPodcastMetadata :one
SELECT
  p.podcast_itunes_id,
  p.title,
  p.description,
  COALESCE(p.author, '') AS author,
  COALESCE(p.image, '') AS image,
  COALESCE(p.feed_url, '') AS feed_url,
  COALESCE(p.language, '') AS language,
  COALESCE(p.categories_json, '') AS categories_json,
  COALESCE(p.episode_count_hint, 0) AS episode_count_hint,
  p.feed_last_update_time_unix,
  p.created_at_unix,
  p.updated_at_unix
FROM podcast_shows p
WHERE p.podcast_itunes_id = ?1
`

type GetPIPodcastMetadataRow struct {
	PodcastItunesID        string
	Title                  string
	Description            string
	Author                 string
	Image                  string
	FeedUrl                string
	Language               string
	CategoriesJson         string
	EpisodeCountHint       int64
	FeedLastUpdateTimeUnix int64
	CreatedAtUnix          int64
	UpdatedAtUnix          int64
}

func (q *Queries) GetPIPodcastMetadata(ctx context.Context, podcastItunesID string) (GetPIPodcastMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getPIPodcastMetadata, podcastItunesID)
	var i GetPIPodcastMetadataRow
	err := row.Scan(
		&i.PodcastItunesID,
		&i.Title,
		&i.Description,
		&i.Author,
		&i.Image,
		&i.FeedUrl,
		&i.Language,
		&i.CategoriesJson,
		&i.EpisodeCountHint,
		&i.FeedLastUpdateTimeUnix,
		&i.CreatedAtUnix,
		&i.UpdatedAtUnix,
	)
	return i, err
}

const getPIPodcastRecord = `-- name: GetPIPodcastRecord :one
SELECT
  p.podcast_itunes_id,
  p.title,
  p.description,
  COALESCE(p.author, '') AS author,
  COALESCE(p.image, '') AS image,
  COALESCE(p.feed_url, '') AS feed_url,
  COALESCE(p.language, '') AS language,
  COALESCE(p.categories_json, '') AS categories_json,
  COALESCE(p.episode_count_hint, 0) AS episode_count_hint,
  p.feed_last_update_time_unix,
  (SELECT COUNT(*) FROM podcast_episodes episodes WHERE episodes.podcast_itunes_id = p.podcast_itunes_id) AS stored_episode_count,
  COALESCE(state.is_truncated, 0) AS is_truncated,
  COALESCE(state.last_successful_fetch_at_unix, 0) AS last_successful_fetch_at_unix,
  COALESCE(state.last_attempted_fetch_at_unix, 0) AS last_attempted_fetch_at_unix,
  COALESCE(state.refresh_not_before_unix, 0) AS refresh_not_before_unix,
  COALESCE(state.fetch_fail_count, 0) AS fetch_fail_count,
  COALESCE(state.last_error_class, '') AS last_error_class,
  COALESCE(state.approx_bytes, 0) AS approx_bytes,
  COALESCE(state.priority, 0) AS priority,
  COALESCE(state.last_accessed_at_unix, 0) AS last_accessed_at_unix,
  p.created_at_unix,
  p.updated_at_unix
FROM podcast_shows p
LEFT JOIN podcast_cache_state state
  ON state.podcast_itunes_id = p.podcast_itunes_id
WHERE p.podcast_itunes_id = ?1
`

type GetPIPodcastRecordRow struct {
	PodcastItunesID           string
	Title                     string
	Description               string
	Author                    string
	Image                     string
	FeedUrl                   string
	Language                  string
	CategoriesJson            string
	EpisodeCountHint          int64
	FeedLastUpdateTimeUnix    int64
	StoredEpisodeCount        int64
	IsTruncated               int64
	LastSuccessfulFetchAtUnix int64
	LastAttemptedFetchAtUnix  int64
	RefreshNotBeforeUnix      int64
	FetchFailCount            int64
	LastErrorClass            string
	ApproxBytes               int64
	Priority                  int64
	LastAccessedAtUnix        int64
	CreatedAtUnix             int64
	UpdatedAtUnix             int64
}

func (q *Queries) GetPIPodcastRecord(ctx context.Context, podcastItunesID string) (GetPIPodcastRecordRow, error) {
	row := q.db.QueryRowContext(ctx, getPIPodcastRecord, podcastItunesID)
	var i GetPIPodcastRecordRow
	err := row.Scan(
		&i.PodcastItunesID,
		&i.Title,
		&i.Description,
		&i.Author,
		&i.Image,
		&i.FeedUrl,
		&i.Language,
		&i.CategoriesJson,
		&i.EpisodeCountHint,
		&i.FeedLastUpdateTimeUnix,
		&i.StoredEpisodeCount,
		&i.IsTruncated,
		&i.LastSuccessfulFetchAtUnix,
		&i.LastAttemptedFetchAtUnix,
		&i.RefreshNotBeforeUnix,
		&i.FetchFailCount,
		&i.LastErrorClass,
		&i.ApproxBytes,
		&i.Priority,
		&i.LastAccessedAtUnix,
		&i.CreatedAtUnix,
		&i.UpdatedAtUnix,
	)
	return i, err
}

const getPIRefreshState = `-- name: GetPIRefreshState :one
SELECT
  state.podcast_itunes_id,
  (SELECT COUNT(*) FROM podcast_episodes episodes WHERE episodes.podcast_itunes_id = state.podcast_itunes_id) AS stored_episode_count,
  state.is_truncated,
  state.last_successful_fetch_at_unix,
  state.last_attempted_fetch_at_unix,
  state.refresh_not_before_unix,
  state.fetch_fail_count,
  COALESCE(state.last_error_class, '') AS last_error_class
FROM podcast_cache_state state
WHERE state.podcast_itunes_id = ?1
`

type GetPIRefreshStateRow struct {
	PodcastItunesID           string
	StoredEpisodeCount        int64
	IsTruncated               int64
	LastSuccessfulFetchAtUnix int64
	LastAttemptedFetchAtUnix  int64
	RefreshNotBeforeUnix      int64
	FetchFailCount            int64
	LastErrorClass            string
}

func (q *Queries) GetPIRefreshState(ctx context.Context, podcastItunesID string) (GetPIRefreshStateRow, error) {
	row := q.db.QueryRowContext(ctx, getPIRefreshState, podcastItunesID)
	var i GetPIRefreshStateRow
	err := row.Scan(
		&i.PodcastItunesID,
		&i.StoredEpisodeCount,
		&i.IsTruncated,
		&i.LastSuccessfulFetchAtUnix,
		&i.LastAttemptedFetchAtUnix,
		&i.RefreshNotBeforeUnix,
		&i.FetchFailCount,
		&i.LastErrorClass,
	)
	return i, err
}

const insertPIEpisode = `-- name: InsertPIEpisode :exec
INSERT INTO podcast_episodes (
  podcast_itunes_id,
  episode_guid,
  title,
  description,
  enclosure_url,
  published_at_unix,
  duration_seconds,
  image,
  episode_number,
  season_number,
  episode_type,
  explicit,
  link,
  enclosure_length,
  transcript_url,
  created_at_unix,
  updated_at_unix
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13,
  ?14,
  ?15,
  ?16,
  ?17
)
`

type InsertPIEpisodeParams struct {
	PodcastItunesID string
	EpisodeGuid     string
	Title           string
	Description     string
	EnclosureUrl    string
	PublishedAtUnix int64
	DurationSeconds int64
	Image           sql.NullString
	EpisodeNumber   sql.NullInt64
	SeasonNumber    sql.NullInt64
	EpisodeType     sql.NullString
	Explicit        sql.NullInt64
	Link            sql.NullString
	EnclosureLength sql.NullInt64
	TranscriptUrl   sql.NullString
	CreatedAtUnix   int64
	UpdatedAtUnix   int64
}

func (q *Queries) InsertPIEpisode(ctx context.Context, arg InsertPIEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, insertPIEpisode,
		arg.PodcastItunesID,
		arg.EpisodeGuid,
		arg.Title,
		arg.Description,
		arg.EnclosureUrl,
		arg.PublishedAtUnix,
		arg.DurationSeconds,
		arg.Image,
		arg.EpisodeNumber,
		arg.SeasonNumber,
		arg.EpisodeType,
		arg.Explicit,
		arg.Link,
		arg.EnclosureLength,
		arg.TranscriptUrl,
		arg.CreatedAtUnix,
		arg.UpdatedAtUnix,
	)
	return err
}

const listPIEpisodes = `-- name: ListPIEpisodes :many
SELECT
  podcast_itunes_id,
  episode_guid,
  title,
  description,
  enclosure_url,
  published_at_unix,
  duration_seconds,
  image,
  episode_number,
  season_number,
  episode_type,
  explicit,
  link,
  enclosure_length,
  transcript_url,
  created_at_unix,
  updated_at_unix
FROM podcast_episodes
WHERE podcast_itunes_id = ?1
ORDER BY published_at_unix DESC, episode_guid ASC
`

func (q *Queries) ListPIEpisodes(ctx context.Context, podcastItunesID string) ([]PodcastEpisode, error) {
	rows, err := q.db.QueryContext(ctx, listPIEpisodes, podcastItunesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PodcastEpisode
	for rows.Next() {
		var i PodcastEpisode
		if err := rows.Scan(
			&i.PodcastItunesID,
			&i.EpisodeGuid,
			&i.Title,
			&i.Description,
			&i.EnclosureUrl,
			&i.PublishedAtUnix,
			&i.DurationSeconds,
			&i.Image,
			&i.EpisodeNumber,
			&i.SeasonNumber,
			&i.EpisodeType,
			&i.Explicit,
			&i.Link,
			&i.EnclosureLength,
			&i.TranscriptUrl,
			&i.CreatedAtUnix,
			&i.UpdatedAtUnix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPIEpisodesPage = `-- name: ListPIEpisodesPage :many
SELECT
  podcast_itunes_id,
  episode_guid,
  title,
  description,
  enclosure_url,
  published_at_unix,
  duration_seconds,
  image,
  episode_number,
  season_number,
  episode_type,
  explicit,
  link,
  enclosure_length,
  transcript_url,
  created_at_unix,
  updated_at_unix
FROM podcast_episodes
WHERE podcast_itunes_id = ?1
ORDER BY published_at_unix DESC, episode_guid ASC
LIMIT ?3 OFFSET ?2
`

type ListPIEpisodesPageParams struct {
	PodcastItunesID string
	Offset          int64
	Limit           int64
}

func (q *Queries) ListPIEpisodesPage(ctx context.Context, arg ListPIEpisodesPageParams) ([]PodcastEpisode, error) {
	rows, err := q.db.QueryContext(ctx, listPIEpisodesPage, arg.PodcastItunesID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PodcastEpisode
	for rows.Next() {
		var i PodcastEpisode
		if err := rows.Scan(
			&i.PodcastItunesID,
			&i.EpisodeGuid,
			&i.Title,
			&i.Description,
			&i.EnclosureUrl,
			&i.PublishedAtUnix,
			&i.DurationSeconds,
			&i.Image,
			&i.EpisodeNumber,
			&i.SeasonNumber,
			&i.EpisodeType,
			&i.Explicit,
			&i.Link,
			&i.EnclosureLength,
			&i.TranscriptUrl,
			&i.CreatedAtUnix,
			&i.UpdatedAtUnix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPIEvictionCandidates = `-- name: ListPIEvictionCandidates :many
SELECT podcast_itunes_id, approx_bytes
FROM podcast_cache_state
ORDER BY priority ASC, last_accessed_at_unix ASC, podcast_itunes_id ASC
`

type ListPIEvictionCandidatesRow struct {
	PodcastItunesID string
	ApproxBytes     int64
}

func (q *Queries) ListPIEvictionCandidates(ctx context.Context) ([]ListPIEvictionCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPIEvictionCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPIEvictionCandidatesRow
	for rows.Next() {
		var i ListPIEvictionCandidatesRow
		if err := rows.Scan(&i.PodcastItunesID, &i.ApproxBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPIRefreshFailure = `-- name: MarkPIRefreshFailure :exec
UPDATE podcast_cache_state
SET last_attempted_fetch_at_unix = ?1,
  refresh_not_before_unix = ?2,
  fetch_fail_count = ?3,
  last_error_class = ?4
WHERE podcast_itunes_id = ?5
`

type MarkPIRefreshFailureParams struct {
	LastAttemptedFetchAtUnix int64
	RefreshNotBeforeUnix     int64
	FetchFailCount           int64
	LastErrorClass           sql.NullString
	PodcastItunesID          string
}

func (q *Queries) MarkPIRefreshFailure(ctx context.Context, arg MarkPIRefreshFailureParams) error {
	_, err := q.db.ExecContext(ctx, markPIRefreshFailure,
		arg.LastAttemptedFetchAtUnix,
		arg.RefreshNotBeforeUnix,
		arg.FetchFailCount,
		arg.LastErrorClass,
		arg.PodcastItunesID,
	)
	return err
}

const touchPIPodcastAccess = `-- name: TouchPIPodcastAccess :exec
UPDATE podcast_cache_state
SET last_accessed_at_unix = ?1
WHERE podcast_itunes_id = ?2
`

type TouchPIPodcastAccessParams struct {
	LastAccessedAtUnix int64
	PodcastItunesID    string
}

func (q *Queries) TouchPIPodcastAccess(ctx context.Context, arg TouchPIPodcastAccessParams) error {
	_, err := q.db.ExecContext(ctx, touchPIPodcastAccess, arg.LastAccessedAtUnix, arg.PodcastItunesID)
	return err
}

const updatePIApproxBytes = `-- name: UpdatePIApproxBytes :exec
UPDATE podcast_cache_state
SET approx_bytes = (
  SELECT
    CAST(?1 AS INTEGER) +
    length(CAST(p.podcast_itunes_id AS BLOB)) +
    length(CAST(p.title AS BLOB)) +
    length(CAST(p.description AS BLOB)) +
    length(CAST(COALESCE(p.author, '') AS BLOB)) +
    length(CAST(COALESCE(p.image, '') AS BLOB)) +
    length(CAST(COALESCE(p.feed_url, '') AS BLOB)) +
    length(CAST(COALESCE(p.language, '') AS BLOB)) +
    length(CAST(COALESCE(p.categories_json, '') AS BLOB)) +
    COALESCE((
      SELECT SUM(
        CAST(?2 AS INTEGER) +
        length(CAST(e.podcast_itunes_id AS BLOB)) +
        length(CAST(e.episode_guid AS BLOB)) +
        length(CAST(e.title AS BLOB)) +
        length(CAST(e.description AS BLOB)) +
        length(CAST(e.enclosure_url AS BLOB)) +
        length(CAST(COALESCE(e.image, '') AS BLOB)) +
        length(CAST(COALESCE(e.episode_type, '') AS BLOB)) +
        length(CAST(COALESCE(e.link, '') AS BLOB)) +
        length(CAST(COALESCE(e.transcript_url, '') AS BLOB))
      )
      FROM podcast_episodes e
      WHERE e.podcast_itunes_id = p.podcast_itunes_id
    ), 0)
  FROM podcast_shows p
  WHERE p.podcast_itunes_id = podcast_cache_state.podcast_itunes_id
)
WHERE podcast_cache_state.podcast_itunes_id = ?3
`

type UpdatePIApproxBytesParams struct {
	PodcastRowOverhead int64
	EpisodeRowOverhead int64
	PodcastItunesID    string
}

func (q *Queries) UpdatePIApproxBytes(ctx context.Context, arg UpdatePIApproxBytesParams) error {
	_, err := q.db.ExecContext(ctx, updatePIApproxBytes, arg.PodcastRowOverhead, arg.EpisodeRowOverhead, arg.PodcastItunesID)
	return err
}

const upsertPIEpisode = `-- name: UpsertPIEpisode :exec
INSERT INTO podcast_episodes (
  podcast_itunes_id,
  episode_guid,
  title,
  description,
  enclosure_url,
  published_at_unix,
  duration_seconds,
  image,
  episode_number,
  season_number,
  episode_type,
  explicit,
  link,
  enclosure_length,
  transcript_url,
  created_at_unix,
  updated_at_unix
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13,
  ?14,
  ?15,
  ?16,
  ?17
)
ON CONFLICT(podcast_itunes_id, episode_guid) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  enclosure_url = excluded.enclosure_url,
  published_at_unix = excluded.published_at_unix,
  duration_seconds = excluded.duration_seconds,
  image = excluded.image,
  episode_number = excluded.episode_number,
  season_number = excluded.season_number,
  episode_type = excluded.episode_type,
  explicit = excluded.explicit,
  link = excluded.link,
  enclosure_length = excluded.enclosure_length,
  transcript_url = excluded.transcript_url,
  updated_at_unix = excluded.updated_at_unix
`

type UpsertPIEpisodeParams struct {
	PodcastItunesID string
	EpisodeGuid     string
	Title           string
	Description     string
	EnclosureUrl    string
	PublishedAtUnix int64
	DurationSeconds int64
	Image           sql.NullString
	EpisodeNumber   sql.NullInt64
	SeasonNumber    sql.NullInt64
	EpisodeType     sql.NullString
	Explicit        sql.NullInt64
	Link            sql.NullString
	EnclosureLength sql.NullInt64
	TranscriptUrl   sql.NullString
	CreatedAtUnix   int64
	UpdatedAtUnix   int64
}

func (q *Queries) UpsertPIEpisode(ctx context.Context, arg UpsertPIEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, upsertPIEpisode,
		arg.PodcastItunesID,
		arg.EpisodeGuid,
		arg.Title,
		arg.Description,
		arg.EnclosureUrl,
		arg.PublishedAtUnix,
		arg.DurationSeconds,
		arg.Image,
		arg.EpisodeNumber,
		arg.SeasonNumber,
		arg.EpisodeType,
		arg.Explicit,
		arg.Link,
		arg.EnclosureLength,
		arg.TranscriptUrl,
		arg.CreatedAtUnix,
		arg.UpdatedAtUnix,
	)
	return err
}

const upsertPIFullCacheState = `-- name: UpsertPIFullCacheState :exec
INSERT INTO podcast_cache_state (
  podcast_itunes_id,
  is_truncated,
  last_successful_fetch_at_unix,
  last_attempted_fetch_at_unix,
  refresh_not_before_unix,
  fetch_fail_count,
  last_error_class,
  approx_bytes,
  priority,
  last_accessed_at_unix
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10
)
ON CONFLICT(podcast_itunes_id) DO UPDATE SET
  is_truncated = excluded.is_truncated,
  last_successful_fetch_at_unix = excluded.last_successful_fetch_at_unix,
  last_attempted_fetch_at_unix = excluded.last_attempted_fetch_at_unix,
  refresh_not_before_unix = excluded.refresh_not_before_unix,
  fetch_fail_count = excluded.fetch_fail_count,
  last_error_class = excluded.last_error_class,
  approx_bytes = excluded.approx_bytes,
  priority = excluded.priority,
  last_accessed_at_unix = excluded.last_accessed_at_unix
`

type UpsertPIFullCacheStateParams struct {
	PodcastItunesID           string
	IsTruncated               int64
	LastSuccessfulFetchAtUnix int64
	LastAttemptedFetchAtUnix  int64
	RefreshNotBeforeUnix      int64
	FetchFailCount            int64
	LastErrorClass            sql.NullString
	ApproxBytes               int64
	Priority                  int64
	LastAccessedAtUnix        int64
}

func (q *Queries) UpsertPIFullCacheState(ctx context.Context, arg UpsertPIFullCacheStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertPIFullCacheState,
		arg.PodcastItunesID,
		arg.IsTruncated,
		arg.LastSuccessfulFetchAtUnix,
		arg.LastAttemptedFetchAtUnix,
		arg.RefreshNotBeforeUnix,
		arg.FetchFailCount,
		arg.LastErrorClass,
		arg.ApproxBytes,
		arg.Priority,
		arg.LastAccessedAtUnix,
	)
	return err
}

const upsertPIIncrementalCacheState = `-- name: UpsertPIIncrementalCacheState :exec
INSERT INTO podcast_cache_state (
  podcast_itunes_id,
  is_truncated,
  last_successful_fetch_at_unix,
  last_attempted_fetch_at_unix,
  refresh_not_before_unix,
  fetch_fail_count,
  last_error_class,
  approx_bytes,
  priority,
  last_accessed_at_unix
) VALUES (
  ?1,
  CASE
    WHEN CAST(?2 AS INTEGER) != 0 THEN 1
    WHEN (SELECT COUNT(*) FROM podcast_episodes episodes WHERE episodes.podcast_itunes_id = ?1) >= CAST(?3 AS INTEGER) THEN 1
    WHEN CAST(?4 AS INTEGER) > (SELECT COUNT(*) FROM podcast_episodes episodes WHERE episodes.podcast_itunes_id = ?1) THEN 1
    ELSE 0
  END,
  ?5,
  ?6,
  ?7,
  0,
  NULL,
  0,
  ?8,
  ?9
)
ON CONFLICT(podcast_itunes_id) DO UPDATE SET
  is_truncated = excluded.is_truncated,
  last_successful_fetch_at_unix = excluded.last_successful_fetch_at_unix,
  last_attempted_fetch_at_unix = excluded.last_attempted_fetch_at_unix,
  refresh_not_before_unix = excluded.refresh_not_before_unix,
  fetch_fail_count = excluded.fetch_fail_count,
  last_error_class = excluded.last_error_class,
  priority = podcast_cache_state.priority,
  last_accessed_at_unix = excluded.last_accessed_at_unix
`

type UpsertPIIncrementalCacheStateParams struct {
	PodcastItunesID           string
	PreviouslyTruncated       int64
	MaxEpisodesPerPodcast     int64
	EpisodeCountHint          int64
	LastSuccessfulFetchAtUnix int64
	LastAttemptedFetchAtUnix  int64
	RefreshNotBeforeUnix      int64
	Priority                  int64
	LastAccessedAtUnix        int64
}

func (q *Queries) UpsertPIIncrementalCacheState(ctx context.Context, arg UpsertPIIncrementalCacheStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertPIIncrementalCacheState,
		arg.PodcastItunesID,
		arg.PreviouslyTruncated,
		arg.MaxEpisodesPerPodcast,
		arg.EpisodeCountHint,
		arg.LastSuccessfulFetchAtUnix,
		arg.LastAttemptedFetchAtUnix,
		arg.RefreshNotBeforeUnix,
		arg.Priority,
		arg.LastAccessedAtUnix,
	)
	return err
}

const upsertPIPodcastShow = `-- name: UpsertPIPodcastShow :exec
INSERT INTO podcast_shows (
  podcast_itunes_id,
  title,
  description,
  author,
  image,
  feed_url,
  language,
  categories_json,
  episode_count_hint,
  feed_last_update_time_unix,
  created_at_unix,
  updated_at_unix
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12
)
ON CONFLICT(podcast_itunes_id) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  author = excluded.author,
  image = excluded.image,
  feed_url = excluded.feed_url,
  language = excluded.language,
  categories_json = excluded.categories_json,
  episode_count_hint = excluded.episode_count_hint,
  feed_last_update_time_unix = excluded.feed_last_update_time_unix,
  updated_at_unix = excluded.updated_at_unix
`

type UpsertPIPodcastShowParams struct {
	PodcastItunesID        string
	Title                  string
	Description            string
	Author                 sql.NullString
	Image                  sql.NullString
	FeedUrl                sql.NullString
	Language               sql.NullString
	CategoriesJson         sql.NullString
	EpisodeCountHint       sql.NullInt64
	FeedLastUpdateTimeUnix int64
	CreatedAtUnix          int64
	UpdatedAtUnix          int64
}

func (q *Queries) UpsertPIPodcastShow(ctx context.Context, arg UpsertPIPodcastShowParams) error {
	_, err := q.db.ExecContext(ctx, upsertPIPodcastShow,
		arg.PodcastItunesID,
		arg.Title,
		arg.Description,
		arg.Author,
		arg.Image,
		arg.FeedUrl,
		arg.Language,
		arg.CategoriesJson,
		arg.EpisodeCountHint,
		arg.FeedLastUpdateTimeUnix,
		arg.CreatedAtUnix,
		arg.UpdatedAtUnix,
	)
	return err
}
