/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FilesRouteImport } from './routes/files'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as PodcastIdRouteImport } from './routes/podcast/$id'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as PodcastIdIndexRouteImport } from './routes/podcast/$id/index'
import { Route as PodcastIdEpisodesRouteImport } from './routes/podcast/$id/episodes'
import { Route as FilesFolderFolderIdRouteImport } from './routes/files/folder/$folderId'
import { Route as PodcastIdEpisodeEpisodeIdRouteImport } from './routes/podcast/$id/episode/$episodeId'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilesRoute,
} as any)
const PodcastIdRoute = PodcastIdRouteImport.update({
  id: '/podcast/$id',
  path: '/podcast/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const PodcastIdIndexRoute = PodcastIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PodcastIdRoute,
} as any)
const PodcastIdEpisodesRoute = PodcastIdEpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => PodcastIdRoute,
} as any)
const FilesFolderFolderIdRoute = FilesFolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => FilesRoute,
} as any)
const PodcastIdEpisodeEpisodeIdRoute =
  PodcastIdEpisodeEpisodeIdRouteImport.update({
    id: '/episode/$episodeId',
    path: '/episode/$episodeId',
    getParentRoute: () => PodcastIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/files': typeof FilesRouteWithChildren
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/podcast/$id': typeof PodcastIdRouteWithChildren
  '/files/': typeof FilesIndexRoute
  '/files/folder/$folderId': typeof FilesFolderFolderIdRoute
  '/podcast/$id/episodes': typeof PodcastIdEpisodesRoute
  '/podcast/$id/': typeof PodcastIdIndexRoute
  '/podcast/$id/episode/$episodeId': typeof PodcastIdEpisodeEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/files': typeof FilesIndexRoute
  '/files/folder/$folderId': typeof FilesFolderFolderIdRoute
  '/podcast/$id/episodes': typeof PodcastIdEpisodesRoute
  '/podcast/$id': typeof PodcastIdIndexRoute
  '/podcast/$id/episode/$episodeId': typeof PodcastIdEpisodeEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/files': typeof FilesRouteWithChildren
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/podcast/$id': typeof PodcastIdRouteWithChildren
  '/files/': typeof FilesIndexRoute
  '/files/folder/$folderId': typeof FilesFolderFolderIdRoute
  '/podcast/$id/episodes': typeof PodcastIdEpisodesRoute
  '/podcast/$id/': typeof PodcastIdIndexRoute
  '/podcast/$id/episode/$episodeId': typeof PodcastIdEpisodeEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/favorites'
    | '/files'
    | '/history'
    | '/legal'
    | '/search'
    | '/settings'
    | '/subscriptions'
    | '/legal/privacy'
    | '/legal/terms'
    | '/podcast/$id'
    | '/files/'
    | '/files/folder/$folderId'
    | '/podcast/$id/episodes'
    | '/podcast/$id/'
    | '/podcast/$id/episode/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/favorites'
    | '/history'
    | '/legal'
    | '/search'
    | '/settings'
    | '/subscriptions'
    | '/legal/privacy'
    | '/legal/terms'
    | '/files'
    | '/files/folder/$folderId'
    | '/podcast/$id/episodes'
    | '/podcast/$id'
    | '/podcast/$id/episode/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/favorites'
    | '/files'
    | '/history'
    | '/legal'
    | '/search'
    | '/settings'
    | '/subscriptions'
    | '/legal/privacy'
    | '/legal/terms'
    | '/podcast/$id'
    | '/files/'
    | '/files/folder/$folderId'
    | '/podcast/$id/episodes'
    | '/podcast/$id/'
    | '/podcast/$id/episode/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  FilesRoute: typeof FilesRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  LegalRoute: typeof LegalRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  PodcastIdRoute: typeof PodcastIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof FilesRoute
    }
    '/podcast/$id': {
      id: '/podcast/$id'
      path: '/podcast/$id'
      fullPath: '/podcast/$id'
      preLoaderRoute: typeof PodcastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/podcast/$id/': {
      id: '/podcast/$id/'
      path: '/'
      fullPath: '/podcast/$id/'
      preLoaderRoute: typeof PodcastIdIndexRouteImport
      parentRoute: typeof PodcastIdRoute
    }
    '/podcast/$id/episodes': {
      id: '/podcast/$id/episodes'
      path: '/episodes'
      fullPath: '/podcast/$id/episodes'
      preLoaderRoute: typeof PodcastIdEpisodesRouteImport
      parentRoute: typeof PodcastIdRoute
    }
    '/files/folder/$folderId': {
      id: '/files/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/files/folder/$folderId'
      preLoaderRoute: typeof FilesFolderFolderIdRouteImport
      parentRoute: typeof FilesRoute
    }
    '/podcast/$id/episode/$episodeId': {
      id: '/podcast/$id/episode/$episodeId'
      path: '/episode/$episodeId'
      fullPath: '/podcast/$id/episode/$episodeId'
      preLoaderRoute: typeof PodcastIdEpisodeEpisodeIdRouteImport
      parentRoute: typeof PodcastIdRoute
    }
  }
}

interface FilesRouteChildren {
  FilesIndexRoute: typeof FilesIndexRoute
  FilesFolderFolderIdRoute: typeof FilesFolderFolderIdRoute
}

const FilesRouteChildren: FilesRouteChildren = {
  FilesIndexRoute: FilesIndexRoute,
  FilesFolderFolderIdRoute: FilesFolderFolderIdRoute,
}

const FilesRouteWithChildren = FilesRoute._addFileChildren(FilesRouteChildren)

interface LegalRouteChildren {
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface PodcastIdRouteChildren {
  PodcastIdEpisodesRoute: typeof PodcastIdEpisodesRoute
  PodcastIdIndexRoute: typeof PodcastIdIndexRoute
  PodcastIdEpisodeEpisodeIdRoute: typeof PodcastIdEpisodeEpisodeIdRoute
}

const PodcastIdRouteChildren: PodcastIdRouteChildren = {
  PodcastIdEpisodesRoute: PodcastIdEpisodesRoute,
  PodcastIdIndexRoute: PodcastIdIndexRoute,
  PodcastIdEpisodeEpisodeIdRoute: PodcastIdEpisodeEpisodeIdRoute,
}

const PodcastIdRouteWithChildren = PodcastIdRoute._addFileChildren(
  PodcastIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  FilesRoute: FilesRouteWithChildren,
  HistoryRoute: HistoryRoute,
  LegalRoute: LegalRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  PodcastIdRoute: PodcastIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
