services:
  readio-api:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/readio-cloud-api:latest
    container_name: readio-api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /etc/readio:/etc/readio
    env_file:
      - /etc/readio/readio.env
    environment:
      - READIO_CLOUD_DB_PATH=/etc/readio/readio.db
    logging:
      # Keep logs manageable
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
